In [1]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
num_classes = 10
input_shape = (28, 28, 1)

In [4]:
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()

In [6]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

print('X_train shape', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

X_train shape (60000, 28, 28, 1, 1)
60000 train samples
10000 test samples


In [7]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [8]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [11]:
model = keras.Sequential(
        [
            keras.Input(shape = input_shape),
            layers.Conv2D(32, kernel_size=(3,3), activation='relu'),
            layers.MaxPooling2D(pool_size=(2,2)),
            layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
            layers.MaxPooling2D(pool_size=(2,2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation='softmax'),
        ]
)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
flatten (Flatten)            (None, 1600)              0         
_________________________________________________________________
dropout (Dropout)            (None, 1600)              0         
_________________________________________________________________
dense (Dense)                (None, 10)                1

In [12]:
batch_size = 128
epochs = 15

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/15
375/375 [==============================] - 13s 33ms/step - loss: 1.5491 - accuracy: 0.5130 - val_loss: 0.5776 - val_accuracy: 0.8367
Epoch 2/15
375/375 [==============================] - 13s 34ms/step - loss: 0.5592 - accuracy: 0.8264 - val_loss: 0.3606 - val_accuracy: 0.8970
Epoch 3/15
375/375 [==============================] - 13s 35ms/step - loss: 0.4180 - accuracy: 0.8741 - val_loss: 0.2799 - val_accuracy: 0.9224
Epoch 4/15
375/375 [==============================] - 13s 35ms/step - loss: 0.3414 - accuracy: 0.8995 - val_loss: 0.2252 - val_accuracy: 0.9395
Epoch 5/15
375/375 [==============================] - 15s 39ms/step - loss: 0.2942 - accuracy: 0.9129 - val_loss: 0.1900 - val_accuracy: 0.9495
Epoch 6/15
375/375 [==============================] - 15s 39ms/step - loss: 0.2613 - accuracy: 0.9210 - val_loss: 0.1692 - val_accuracy: 0.9534
Epoch 7/15
375/375 [==============================] - 15s 39ms/step - loss: 0.2377 - accuracy: 0.9271 - val_loss: 0.1483 - val_accuracy:

In [13]:
score = model.evaluate(X_test, y_test)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

313/313 [==============================] - 1s 3ms/step - loss: 0.0950 - accuracy: 0.9717
Test loss: 0.09500071406364441
Test accuracy: 0.9717000126838684
